services:
  node:
    container_name: nextjs-todo-app-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todoapp
    networks:
      - mynetwork
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb_dev
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
