services:
  node:
    container_name: nextjs-todo-app-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todoapp
    networks:
      - mynetwork
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
